#!/usr/bin/bash

test -z "$key_database_dir" && export key_database_dir="$HOME/.key_database"
test -e "/tmp/keys_$USER.lock" && { echo "locked: wait until changes are done or delete /tmp/keys_$USER.lock if something unexpected happened"; exit 1; }

create() {
	test -e "$key_database_dir"/key_database && { echo ""$key_database_dir"/key_database already exists"; exit 1; }
	database="/tmp/key_database_$USER"
	touch "$database"
	chmod 600 "$database"
	echo "title	username	password	totp	note" > "$database"
	test -e "$key_database_dir" || mkdir "$key_database_dir"
	scrypt enc --passphrase dev:stdin-once --logN 20 -r8 -p8 "$database" "$key_database_dir"/key_database
	cd "$key_database_dir"
	git init
	git add key_database
	git commit -m "create database"
	echo "created at "$key_database_dir"/key_database"		
}
update() {
	open || { close; exit 1; }
	database="/tmp/key_database_$USER"

	pw=$(cat "/tmp/key_pw_$USER")
	
	{
		touch "/tmp/keys_$USER.lock"
		chmod 600 "/tmp/keys_$USER.lock"
		echo "doing changes to the database... important: do not delete or change any temporary files now"
		cp "$key_database_dir"/key_database "$key_database_dir"/key_database.bkup
		scrypt enc --passphrase file:"/tmp/key_pw_$USER" --logN 20 -r8 -p8 "$database" "$key_database_dir"/key_database >/dev/null 2>&1
		cd "$key_database_dir"
		git add key_database key_database.bkup
		git commit -m "database edit" >/dev/null 2>&1
		rm -f "/tmp/keys_$USER.lock"
	} &
}
open() {
	test -e "$key_database_dir"/key_database || { echo ""$key_database_dir"/key_database does not exist"; exit 1; }
	
	test -e "/tmp/key_database_$USER" && { echo "open database found"; return; }
	
	database="/tmp/key_database_$USER"
	touch "$database"
	chmod 600 "$database"
	
	if test -e "/tmp/key_pw_$USER"; then
		pw=$(cat "/tmp/key_pw_$USER");
		scrypt dec --passphrase file:"/tmp/key_pw_$USER" "$key_database_dir"/key_database "$database" || { 
			echo "failure"; rm "/tmp/key_pw_$USER"; rm "$database"; exit 1; 
		} 
		return
	fi
	
	if test -z "$1"; then
		echo -n "type your password: "
		read -s pw
		echo "checking the key..."
		touch "/tmp/key_pw_$USER"
		chmod 600 "/tmp/key_pw_$USER"
		echo -n "$pw" > "/tmp/key_pw_$USER"
	else
		touch "/tmp/key_pw_$USER"
		chmod 600 "/tmp/key_pw_$USER"
		echo -n "$(cat $1)" > "/tmp/key_pw_$USER"
	fi

	scrypt dec --passphrase file:"/tmp/key_pw_$USER" "$key_database_dir"/key_database "$database" || { 
		echo "failure"; rm "/tmp/key_pw_$USER"; rm "$database"; exit 1; 
	}
}
close() {
	rm -f "/tmp/key_database_$USER"
	rm -f "/tmp/key_pw_$USER"
	echo "closed"
}
list() {
	open || { close; exit 1; }
	cat "/tmp/key_database_$USER" | sed 1d | awk -F $'\t' '{print $1" "$2" "$5}' | nl -w1 -s". "
}
add() {
	open || { close; exit 1; }
	database="/tmp/key_database_$USER"
	
	echo -n "type the new title: "
	read title || exit 1
	echo -n "type the new username: "
	read username || exit 1
	echo -n "type the new password (empty for autogeneration): "
	read -s password 
	test -z "$password" && { echo ""; password=$(cat /dev/urandom | tr -dc '[:graph:]' | head -c 20); }
	echo -n "type the new TOTP key: "
	read totp || exit 1
	echo -n "type a note: "
	read note || exit 1
	
	echo -e "$title\t$username\t$password\t$totp\t$note" >> "/tmp/key_database_$USER"
	
	update
}
remove() {
	open || { close; exit 1; }
	database="/tmp/key_database_$USER"

    regex='^[0-9]+$'
    if [[ $1 =~ $regex ]]; then
    	n=$(($1 + 1))
		bkup=$(sed -n "$n"p $database)
		name=$(sed -n "$n"p $database | awk -F $'\t' '{print $1" "$2}' | tr -d '\n')
    	read -p "are you sure you want to delete '$name'?" || exit 1
		install -m 600 /dev/null "/tmp/keys_deleted_entry_$USER"
		echo "$bkup" >> "/tmp/keys_deleted_entry_$USER"
		echo "deleted entry '$name', backup in /tmp/keys_deleted_entry_$USER"
		sed -i "$n"d $database
	else
		echo "argument should be a digit"
		exit 1
	fi

	update
}
get() {
	open >/dev/null 2>&1 || { close; exit 1; }
	database="/tmp/key_database_$USER"

    regex='^[0-9]+$'
    if [[ $1 =~ $regex ]]; then
    	n=$(($1 + 1))
		sed -n "$n"p $database | awk -F $'\t' '{print $3}' | tr -d '\n'
	else
		echo "argument should be a digit"
	fi
}
edit() {
	open || { close; exit 1; }
	database="/tmp/key_database_$USER"
	$EDITOR $database
	update	
}

test -s "/tmp/key_database_$USER" || close
test -s "/tmp/key_pw_$USER" || close

case "$1" in 
	"create")
		create
		;;
	"update")
		update
		;;
	"open")
		open "$2"
		;;
	"close")
		close
		;;
	"list")
		list
		;;
	"add")
		add
		;;
	"remove")
		remove $2
		;;
	"edit")
		edit
		;;
	"get")
		get $2
		;;
	*)
		echo "not a valid option (create/update/open/close/list/add/remove/edit)"
		;;
esac
