#!/usr/bin/bash
test -e "$HOME"/.key_database/key_database && { echo ""$HOME"/.key_database/key_database already exists"; exit 1; }
database="/tmp/key_database_$USER"
touch "$database"
chmod 600 "$database"
echo "title	username	password	totp	note" > "$database"
test -e "$HOME"/.key_database || mkdir "$HOME"/.key_database
scrypt enc --passphrase dev:stdin-once --logN 20 -r8 -p8 "$database" "$HOME"/.key_database/key_database
cd "$HOME"/.key_database
git init
git add key_database
git commit -m "create database"
echo "created at "$HOME"/.key_database/key_database"
