#!/usr/bin/bash
/usr/local/bin/keys_open || exit
database="/tmp/key_database_$USER"

pw=$(cat "/tmp/key_pw_$USER")
scrypt enc --passphrase file:"/tmp/key_pw_$USER" --logN 18 -r8 -p8 "$database" "$HOME"/.key_database/key_database
cd "$HOME"/.key_database
git add key_database
git commit -m "database edit"
