#!/usr/bin/bash

test -e "$HOME"/.key_database/key_database || { echo ""$HOME"/.key_database/key_database does not exist"; exit 1; }

test -e "/tmp/key_database_$USER" && { echo "open database found"; exit 0; }

database="/tmp/key_database_$USER"
touch "$database"
chmod 600 "$database"
test -e "/tmp/key_pw_$USER" && { 
	pw=$(cat "/tmp/key_pw_$USER");
	scrypt dec --passphrase file:"/tmp/key_pw_$USER" "$HOME"/.key_database/key_database "$database" || { 
		echo "failure"; rm "/tmp/key_pw_$USER"; exit 1; 
	} 
	exit 0
}
echo -n "type your password: "
read -s pw
echo "checking the key..."
touch "/tmp/key_pw_$USER"
chmod 600 "/tmp/key_pw_$USER"
echo -n "$pw" > "/tmp/key_pw_$USER"

scrypt dec --passphrase file:"/tmp/key_pw_$USER" "$HOME"/.key_database/key_database "$database" || { 
	echo "failure"; rm "/tmp/key_pw_$USER"; exit 1; 
} 

